import type { CharacterProfile, InventoryItem } from "./coc_multiagents_system/agents/models/gameTypes.js";
import { InventoryUtils } from "./coc_multiagents_system/agents/models/gameTypes.js";
import type { ScenarioSnapshot } from "./coc_multiagents_system/agents/models/scenarioTypes.js";
import { actionRules } from "./coc_multiagents_system/rules/index.js";
import type { Evidence } from "./coc_multiagents_system/agents/memory/RagManager.js";

export type AgentId = "keeper" | "memory" | "action";

export type Phase = "intro" | "investigation" | "confrontation" | "downtime";

export type ActionType = 
  | "exploration"      // Discovering clues, understanding environment, gathering information
  | "social"          // Influencing NPCs, gathering intelligence, reaching consensus
  | "stealth"         // Acting without being detected
  | "combat"          // Causing damage, subduing or stopping opponents
  | "chase"           // Extending or closing distance
  | "mental"          // Withstanding or resisting psychological shock
  | "environmental"   // Confronting environment and physiological limits
  | "narrative";      // Making key choices

export interface ActionAnalysis {
  character: string;
  action: string;
  actionType: ActionType;
  target: {
    name: string | null;
    intent: string;
  };
  requiresDice: boolean;  // Whether dice roll is required
}

export type NPCResponseType = 
  | "none"              // No response
  | ActionType;         // One of the eight action types

export interface NPCResponseAnalysis {
  npcName: string;
  willRespond: boolean;  // Whether the NPC will respond
  responseType: NPCResponseType | null;  // Type of response if willRespond is true (one of the eight action types, or "none")
  responseDescription: string;  // Description of what the NPC will do
  executionOrder: number;  // Execution order (1, 2, 3, 4...) - determines the sequence of NPC actions
  targetCharacter?: string | null;  // Target character if response is directed
  isFirstInteraction?: boolean;  // Whether this is the first interaction with this NPC
  initialRelationship?: {
    relationshipType: "ally" | "enemy" | "neutral" | "friend" | "rival" | "stranger";
    attitude: number;  // -30 to +30 for initial relationship
    description: string;
  };
  attitudeChange?: number;  // -100 to +5, attitude change for this interaction
}

export interface SceneChangeRequest {
  shouldChange: boolean;        // Whether scene change is needed
  targetSceneName: string | null;  // Target scene name (generated by LLM)
  reason: string;               // Reason for scene change
  timestamp: Date;              // Request time
}

export interface SceneTransitionRejection {
  wasRequested: boolean;        // Whether scene transition request was rejected
  reasoning: string;            // Director's reason for rejection
  timestamp: Date;              // Rejection time
}

export interface VisitedScenarioBasic {
  id: string;
  name: string;
  location: string;
}

/**
 * Detailed information about a discovered clue
 */
export interface DiscoveredClue {
  /** Clue text content */
  text: string;
  /** Clue type: scenario clue, NPC clue, or secret */
  type: "scenario" | "npc" | "secret";
  /** Source name (scenario name or NPC name) */
  sourceName: string;
  /** Who discovered this clue */
  discoveredBy: string;
  /** When discovered (ISO format) */
  discoveredAt: string;
  /** Clue category (scenario clues only) */
  category?: "physical" | "witness" | "document" | "environment" | "knowledge" | "observation";
  /** Clue difficulty (scenario clues only) */
  difficulty?: "automatic" | "regular" | "hard" | "extreme";
  /** Discovery method */
  method?: string;
}

export interface GameState {
  sessionId: string;
  phase: Phase;
  currentScenario: ScenarioSnapshot | null;
  visitedScenarios: VisitedScenarioBasic[];
  gameDay: number;  // Day number in game
  timeOfDay: string;  // Game time in HH:MM format
  tension: number;
  keeperGuidance: string | null;  // Module keeper guidance (permanent information)
  moduleLimitations: string | null;  // Module limitation conditions (permanent information)
  discoveredClues: DiscoveredClue[];
  playerCharacter: CharacterProfile;
  npcCharacters: CharacterProfile[];
  // Story progression monitoring
  turnsInCurrentScene: number;  // Tracks turns spent in current scene
  lastPlayerInputTime: Date | null;  // Timestamp of last player input
  scenarioTimeState: {
    sceneStartTime: string;     // Game time when scene started
    playerTimeConsumption: Record<string, {  // Time consumption records for each player
      totalShortActions: number;             // Number of short actions by this player in current scene
      lastActionTime: string;                // Time consumption type of this player's last action
    }>;
  };
  temporaryInfo: {
    rules: string[];
    ragResults: Evidence[];
    contextualData: Record<string, any>;
    actionResults: ActionResult[];
    currentActionAnalysis: ActionAnalysis | null;
    npcResponseAnalyses: NPCResponseAnalysis[];  // NPC feedback analyses
    directorDecision: DirectorDecision | null;
    sceneChangeRequest: SceneChangeRequest | null;
    transition: boolean;  // Indicates if a scene change just occurred
    sceneTransitionRejection: SceneTransitionRejection | null;  // Director rejected scene transition
    narrativeDirection: string | null;  // Narrative direction instruction from Director Agent
  };
}

/**
 * CoC State type for template composition
 * Can be a GameState directly or an object containing gameState
 */
export type CoCState = GameState | { gameState?: GameState; [key: string]: any };

const defaultPlayerCharacter: CharacterProfile = {
  id: "investigator-1",
  name: "Investigator",
  attributes: {
    STR: 50,
    CON: 50,
    DEX: 50,
    APP: 50,
    POW: 50,
    SIZ: 50,
    INT: 50,
    EDU: 50,
  },
  status: {
    hp: 10,
    maxHp: 10,
    sanity: 60,
    maxSanity: 99,
    luck: 50,
    mp: 10,
    conditions: [],
  },
  inventory: [], // InventoryItem[]
  skills: {
    "Spot Hidden": 25,
    Listen: 20,
    "Library Use": 20,
    "Fighting (Brawl)": 25,
    Dodge: 25,
    "Firearms (Handgun)": 20,
  },
  notes: "Auto-generated placeholder character",
  actionLog: [],
};


export const initialGameState: GameState = {
  sessionId: "session-local",
  phase: "intro",
  currentScenario: null,
  visitedScenarios: [],
  gameDay: 1,
  timeOfDay: "08:00",
  tension: 1,
  keeperGuidance: null,
  moduleLimitations: null,
  discoveredClues: [],
  playerCharacter: defaultPlayerCharacter,
  npcCharacters: [],
  turnsInCurrentScene: 0,
  lastPlayerInputTime: null,
  scenarioTimeState: {
    sceneStartTime: "08:00",
    playerTimeConsumption: {},
  },
  temporaryInfo: {
    rules: [],
    ragResults: [],
    contextualData: {},
    actionResults: [],
    currentActionAnalysis: null,
    npcResponseAnalyses: [],
    directorDecision: null,
    sceneChangeRequest: null,
    transition: false,
    sceneTransitionRejection: null,
    narrativeDirection: null,
  },
};

export type TimeConsumption = "instant" | "short" | "scene";

export interface DirectorDecision {
  shouldProgress: boolean;
  targetSnapshotId?: string;  // Specific scene snapshot ID to progress to
  estimatedShortActions?: number | null; // Estimated number of short actions executable in target scene
  increaseShortActionCapBy?: number | null; // When not progressing, increase current scene short action cap
  reasoning: string;          // Reason for progression
  timestamp: Date;            // Decision time
}

export interface ActionResult {
  timestamp: Date;
  gameTime: string;
  timeElapsedMinutes?: number; // Actual minutes consumed by the action
  location: string;
  character: string;
  result: string;
  diceRolls: string[];
  timeConsumption: TimeConsumption;  // Time consumption type of this action
  scenarioChanges?: string[]; // List of permanent changes made to the scenario
}

export interface AgentResult {
  agentId: AgentId;
  content: string;
  timestamp: Date;
  metadata?: any;
}

/**
 * GameState Manager - Provides methods to update GameState
 */
export class GameStateManager {
  private gameState: GameState;

  constructor(gameState: GameState) {
    this.gameState = gameState;
  }

  /**
   * Update or add NPCs to the game state (adds all NPCs without filtering)
   */
  updateNpcs(npcData: CharacterProfile[]): void {
    if (!npcData || npcData.length === 0) return;

    for (const newNpc of npcData) {
      const existingIndex = this.gameState.npcCharacters.findIndex(
        npc => npc.id === newNpc.id
      );
      
      if (existingIndex >= 0) {
        // Update existing NPC
        this.gameState.npcCharacters[existingIndex] = newNpc;
      } else {
        // Add new NPC
        this.gameState.npcCharacters.push(newNpc);
      }
    }
  }

  /**
   * Update current scenario and manage visited scenarios history
   */
  updateCurrentScenario(scenarioData: { snapshot: ScenarioSnapshot; scenarioName: string } | null): void {
    if (!scenarioData) return;

    const newScenario = scenarioData.snapshot;
    
    // If we already have a current scenario, move it to visited scenarios
    if (this.gameState.currentScenario) {
      this.addVisitedScenario(this.gameState.currentScenario);
    }

    // Set new current scenario
    this.gameState.currentScenario = newScenario;
    
    // Automatically update NPC locations in the scene
    this.updateNpcLocationsForScenario(newScenario);
    
    // Reset time consumption state for any scenario update (location change OR time progression)
    this.resetScenarioTimeState();
    
    // Reset progression monitor on scenario change
    if (this.progressionMonitor) {
      this.progressionMonitor.resetOnScenarioChange();
    }
  }

  /**
   * Normalize name (for fuzzy matching)
   */
  private normalizeName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, " ")
      .trim();
  }

  /**
   * Calculate Levenshtein distance (edit distance) between two strings
   */
  private levenshtein(a: string, b: string): number {
    const m = a.length;
    const n = b.length;
    const dp: number[][] = Array.from({ length: m + 1 }, () =>
      Array(n + 1).fill(0)
    );

    for (let i = 0; i <= m; i++) dp[i][0] = i;
    for (let j = 0; j <= n; j++) dp[0][j] = j;

    for (let i = 1; i <= m; i++) {
      for (let j = 1; j <= n; j++) {
        const cost = a[i - 1] === b[j - 1] ? 0 : 1;
        dp[i][j] = Math.min(
          dp[i - 1][j] + 1,
          dp[i][j - 1] + 1,
          dp[i - 1][j - 1] + cost
        );
      }
    }
    return dp[m][n];
  }

  /**
   * Determine if two names are similar (similarity >= 80%)
   */
  private isNameSimilar(name1: string, name2: string): boolean {
    const na = this.normalizeName(name1);
    const nb = this.normalizeName(name2);
    if (!na || !nb) return false;
    if (na === nb) return true;

    // If first word is the same, consider similar
    const tokensA = na.split(/\s+/);
    const tokensB = nb.split(/\s+/);
    if (tokensA[0] && tokensA[0] === tokensB[0]) return true;

    // Calculate Levenshtein distance and convert to similarity
    const dist = this.levenshtein(na, nb);
    const maxLen = Math.max(na.length, nb.length);
    if (maxLen === 0) return false;
    const similarity = 1 - dist / maxLen;
    return similarity >= 0.8; // 80% similarity threshold
  }

  /**
   * Automatically update NPC current locations based on character list in scenario
   */
  private updateNpcLocationsForScenario(scenario: ScenarioSnapshot): void {
    if (!scenario || !scenario.characters || scenario.characters.length === 0) {
      return;
    }

    const scenarioLocation = scenario.location;
    const scenarioCharacters = scenario.characters;

    // Iterate through characters in scene, update matching NPC locations
    for (const scenarioChar of scenarioCharacters) {
      // Find matching character in NPC list (using 80% similarity fuzzy matching)
      const matchingNpc = this.gameState.npcCharacters.find(npc => {
        return this.isNameSimilar(npc.name, scenarioChar.name);
      });

      if (matchingNpc) {
        const npcProfile = matchingNpc as any; // NPCProfile
        const oldLocation = npcProfile.currentLocation || null;
        npcProfile.currentLocation = scenarioLocation;
        
        if (oldLocation !== scenarioLocation) {
          const oldLocationDisplay = oldLocation || "Unknown";
          console.log(`📍 [Scene Transition] NPC ${matchingNpc.name} location updated: ${oldLocationDisplay} → ${scenarioLocation}`);
        }
      }
    }
  }

  /**
   * Add a scenario snapshot to the visited list while keeping the list bounded
   */
  addVisitedScenario(scenario: ScenarioSnapshot): void {
    // Check if this scenario is already in visited list
    const existingIndex = this.gameState.visitedScenarios.findIndex(
      visited => visited.id === scenario.id
    );
    
    if (existingIndex === -1) {
      // Extract only basic information for visited scenarios
      const basicScenario: VisitedScenarioBasic = {
        id: scenario.id,
        name: scenario.name,
        location: scenario.location
      };
      
      // Add scenario to visited list
      this.gameState.visitedScenarios.unshift(basicScenario);
      
      // Keep only the most recent 3 visited scenarios
      if (this.gameState.visitedScenarios.length > 3) {
        this.gameState.visitedScenarios = this.gameState.visitedScenarios.slice(0, 3);
      }
    }
  }

  /**
   * Add temporary rules to game state
   */
  addTemporaryRules(ruleData: { rules: any[]; count: number }): void {
    if (!ruleData || !ruleData.rules || ruleData.rules.length === 0) return;

    for (const rule of ruleData.rules) {
      const ruleText = `${rule.title}: ${rule.description}`;
      if (!this.gameState.temporaryInfo.rules.includes(ruleText)) {
        this.gameState.temporaryInfo.rules.push(ruleText);
      }
    }
  }

  /**
   * Apply state updates from action agent results
   */
  applyActionUpdate(stateUpdate: any): void {
    if (!stateUpdate) return;

    // Update player character
    if (stateUpdate.playerCharacter) {
      this.updateCharacter(this.gameState.playerCharacter, stateUpdate.playerCharacter);
    }

    // Update NPC characters
    if (stateUpdate.npcCharacters && Array.isArray(stateUpdate.npcCharacters)) {
      for (const npcUpdate of stateUpdate.npcCharacters) {
        const existingNpc = this.gameState.npcCharacters.find(npc => npc.id === npcUpdate.id);
        if (existingNpc) {
          this.updateCharacter(existingNpc, npcUpdate);
        }
      }
    }
  }

  /**
   * Update individual character data
   */
  private updateCharacter(character: any, updates: any): void {
    // Update character name if provided
    if (updates.name) {
      character.name = updates.name;
    }
    
    // Update status values (hp, sanity, mp, etc.)
    if (updates.status) {
      for (const [key, value] of Object.entries(updates.status)) {
        if (typeof value === 'number' && key in character.status) {
          // Apply differential update (e.g., hp: -2 means subtract 2)
          character.status[key] += value;
          
          // Ensure values don't go below 0
          if (character.status[key] < 0) {
            character.status[key] = 0;
          }
        }
      }
    }
    
    // Update attributes if provided
    if (updates.attributes) {
      for (const [key, value] of Object.entries(updates.attributes)) {
        if (typeof value === 'number' && key in character.attributes) {
          character.attributes[key] += value;
        }
      }
    }
    
    // Update skills if provided
    if (updates.skills) {
      for (const [skillName, value] of Object.entries(updates.skills)) {
        if (typeof value === 'number') {
          if (skillName in character.skills) {
            character.skills[skillName] += value;
          } else {
            character.skills[skillName] = value;
          }
        }
      }
    }
    
    // Update inventory if provided
    if (updates.inventory !== undefined) {
      // Normalize existing inventory to InventoryItem[]
      character.inventory = InventoryUtils.normalizeInventory(character.inventory);
      
      if (Array.isArray(updates.inventory)) {
        // Replace entire inventory with InventoryItem[]
        character.inventory = InventoryUtils.normalizeInventory(updates.inventory as InventoryItem[]);
      } else if (typeof updates.inventory === 'object' && !Array.isArray(updates.inventory)) {
        // Support operations like { add: [...], remove: [...] }
        if (updates.inventory.add) {
          const itemsToAdd = Array.isArray(updates.inventory.add) 
            ? updates.inventory.add 
            : [updates.inventory.add];
          character.inventory = InventoryUtils.addItems(
            character.inventory, 
            InventoryUtils.normalizeInventory(itemsToAdd as InventoryItem[])
          );
        }
        
        if (updates.inventory.remove) {
          const itemsToRemove = Array.isArray(updates.inventory.remove)
            ? updates.inventory.remove
            : [updates.inventory.remove];
          character.inventory = InventoryUtils.removeItems(
            character.inventory, 
            InventoryUtils.normalizeInventory(itemsToRemove as InventoryItem[])
          );
        }
      }
    }
  }

  /**
   * Add action result to temporary storage and update player time consumption
   */
  addActionResult(actionResult: ActionResult): void {
    if (!actionResult) return;
    
    // Update player time consumption
    this.updatePlayerTimeConsumption(actionResult.character, actionResult.timeConsumption);
    
    this.gameState.temporaryInfo.actionResults.push(actionResult);
    
    // Keep only the most recent 10 action results to avoid memory bloat
    if (this.gameState.temporaryInfo.actionResults.length > 10) {
      this.gameState.temporaryInfo.actionResults = this.gameState.temporaryInfo.actionResults.slice(-10);
    }

    // Trigger progression monitoring check after adding action
    this.checkProgressionTriggers(actionResult);
  }

  /**
   * Check if progression monitoring should trigger Director Agent
   */
  private checkProgressionTriggers(actionResult: ActionResult): void {
    // This will be implemented by the system using this GameStateManager
    // The actual monitoring logic is in ProgressionMonitor class
    if (this.progressionMonitor) {
      this.progressionMonitor.updateAfterAction(actionResult);
      
      if (this.progressionMonitor.shouldTriggerDirector()) {
        this.triggerDirectorAgent();
      }
    }
  }

  private progressionMonitor: any = null; // Will be set externally

  /**
   * Set the progression monitor instance
   */
  setProgressionMonitor(monitor: any): void {
    this.progressionMonitor = monitor;
  }

  /**
   * Trigger Director Agent (to be implemented by system)
   */
  private triggerDirectorAgent(): void {
    // This method will be overridden or handled by the main system
    console.log("GameStateManager: Director Agent trigger conditions met - should activate Director Agent");
  }

  /**
   * Update player time consumption tracking
   */
  private updatePlayerTimeConsumption(playerName: string, timeConsumption: TimeConsumption): void {
    // Initialize player record if doesn't exist
    if (!this.gameState.scenarioTimeState.playerTimeConsumption[playerName]) {
      this.gameState.scenarioTimeState.playerTimeConsumption[playerName] = {
        totalShortActions: 0,
        lastActionTime: timeConsumption
      };
    }

    const playerTime = this.gameState.scenarioTimeState.playerTimeConsumption[playerName];
    const shortActionCap = this.getScenarioShortActionCap();
    
    // Update based on time consumption type
    switch (timeConsumption) {
      case "instant":
        // Instant actions don't affect time tracking
        playerTime.lastActionTime = timeConsumption;
        break;
        
      case "short":
        // Track short actions count
        playerTime.totalShortActions += 1;
        playerTime.lastActionTime = timeConsumption;
        break;
        
      case "scene":
        // Scene actions are significant time consumers
        // Scene action counts as reaching the short-action cap for this scenario
        playerTime.totalShortActions = Math.max(playerTime.totalShortActions, shortActionCap);
        playerTime.lastActionTime = timeConsumption;
        break;
    }
  }

  /**
   * Short action cap for the current scenario; default to 3 if undefined
   */
  private getScenarioShortActionCap(): number {
    return this.gameState.currentScenario?.estimatedShortActions || 3;
  }

  /**
   * Get player's short action count in current scenario
   */
  getPlayerShortActions(playerName: string): number {
    const playerTime = this.gameState.scenarioTimeState.playerTimeConsumption[playerName];
    return playerTime ? playerTime.totalShortActions : 0;
  }

  /**
   * Get player's last action time consumption
   */
  getPlayerLastActionTime(playerName: string): TimeConsumption | null {
    const playerTime = this.gameState.scenarioTimeState.playerTimeConsumption[playerName];
    return playerTime ? playerTime.lastActionTime as TimeConsumption : null;
  }

  /**
   * Reset time consumption for new scenario (called when scenario changes)
   */
  resetScenarioTimeState(): void {
    this.gameState.scenarioTimeState.playerTimeConsumption = {};
    this.gameState.scenarioTimeState.sceneStartTime = this.gameState.timeOfDay;
    // Reset turn counter on scenario change
    this.gameState.turnsInCurrentScene = 0;
  }

  /**
   * Increment turn counter for current scene
   */
  incrementTurnCounter(): void {
    this.gameState.turnsInCurrentScene += 1;
  }

  /**
   * Get current turn count in scene
   */
  getTurnsInCurrentScene(): number {
    return this.gameState.turnsInCurrentScene;
  }

  /**
   * Update last player input timestamp
   */
  updatePlayerInputTime(): void {
    this.gameState.lastPlayerInputTime = new Date();
  }

  /**
   * Get minutes since last player input
   */
  getMinutesSinceLastInput(): number {
    if (!this.gameState.lastPlayerInputTime) {
      return 0;
    }
    const now = new Date();
    const diffMs = now.getTime() - this.gameState.lastPlayerInputTime.getTime();
    return Math.floor(diffMs / 60000); // Convert to minutes
  }

  /**
   * Calculate dynamic threshold based on tension
   * Lower tension = higher threshold (slower progression)
   * Higher tension = lower threshold (faster progression)
   */
  getProgressionThreshold(): number {
    const tension = this.gameState.tension;
    if (tension <= 3) return 4;      // Low tension (1-3): 4 turns
    if (tension <= 6) return 3;      // Medium tension (4-6): 3 turns
    if (tension <= 8) return 2;      // High tension (7-8): 2 turns
    return 1;                         // Critical tension (9-10): 1 turn
  }

  /**
   * Check if progression should trigger based on turn count OR time elapsed
   * @returns true if either condition is met
   */
  shouldTriggerProgression(): boolean {
    // Check turn count threshold
    const turnsInScene = this.getTurnsInCurrentScene();
    const threshold = this.getProgressionThreshold();

    if (turnsInScene >= threshold) {
      return true;
    }

    // Check time threshold (3 minutes)
    const minutesSinceInput = this.getMinutesSinceLastInput();
    if (minutesSinceInput >= 3) {
      return true;
    }

    return false;
  }

  /**
   * Update game time based on elapsed time in minutes
   */
  updateGameTime(elapsedMinutes: number): void {
    if (!elapsedMinutes || elapsedMinutes <= 0) return;

    // Parse current time "HH:MM"
    const [hours, minutes] = this.gameState.timeOfDay.split(':').map(Number);
    
    // Calculate new time
    let totalMinutes = hours * 60 + minutes + elapsedMinutes;
    
    // Handle day overflow (24 hours = 1440 minutes)
    if (totalMinutes >= 1440) {
      const daysElapsed = Math.floor(totalMinutes / 1440);
      this.gameState.gameDay += daysElapsed;
      totalMinutes = totalMinutes % 1440;
      console.log(`🌅 A new day has dawned! It is now Day ${this.gameState.gameDay}`);
    }
    
    const newHours = Math.floor(totalMinutes / 60);
    const newMinutes = totalMinutes % 60;
    
    // Update time in HH:MM format
    this.gameState.timeOfDay = 
      `${String(newHours).padStart(2, '0')}:${String(newMinutes).padStart(2, '0')}`;
  }

  /**
   * Get human-readable time of day description
   */
  getTimeOfDayDescription(): string {
    const [hours] = this.gameState.timeOfDay.split(':').map(Number);
    
    if (hours >= 5 && hours < 8) return "Dawn";
    if (hours >= 8 && hours < 12) return "Morning";
    if (hours >= 12 && hours < 14) return "Noon";
    if (hours >= 14 && hours < 17) return "Afternoon";
    if (hours >= 17 && hours < 20) return "Evening";
    if (hours >= 20 && hours < 23) return "Night";
    return "Midnight";
  }

  /**
   * Get full game time display with day and time
   */
  getFullGameTime(): string {
    const timeDesc = this.getTimeOfDayDescription();
    return `Day ${this.gameState.gameDay}, ${this.gameState.timeOfDay} (${timeDesc})`;
  }

  /**
   * Update tension level (1-10 scale)
   */
  updateTension(newTension: number): void {
    // Clamp between 1 and 10
    this.gameState.tension = Math.max(1, Math.min(10, Math.round(newTension)));
  }

  /**
   * Clear all action results
   */
  clearActionResults(): void {
    this.gameState.temporaryInfo.actionResults = [];
  }

  /**
   * Set current action analysis from orchestrator
   */
  setActionAnalysis(actionAnalysis: ActionAnalysis | null): void {
    this.gameState.temporaryInfo.currentActionAnalysis = actionAnalysis;
  }

  /**
   * Clear current action analysis
   */
  clearActionAnalysis(): void {
    this.gameState.temporaryInfo.currentActionAnalysis = null;
  }

  /**
   * Set NPC response analyses from character agent
   */
  setNPCResponseAnalyses(analyses: NPCResponseAnalysis[]): void {
    this.gameState.temporaryInfo.npcResponseAnalyses = analyses;
  }

  /**
   * Clear NPC response analyses
   */
  clearNPCResponseAnalyses(): void {
    this.gameState.temporaryInfo.npcResponseAnalyses = [];
  }

  /**
   * Set director decision from director agent
   */
  setDirectorDecision(decision: DirectorDecision): void {
    this.gameState.temporaryInfo.directorDecision = decision;
  }

  /**
   * Clear director decision
   */
  clearDirectorDecision(): void {
    this.gameState.temporaryInfo.directorDecision = null;
  }

  /**
   * Set scene change request from action agent
   */
  setSceneChangeRequest(request: SceneChangeRequest | null): void {
    this.gameState.temporaryInfo.sceneChangeRequest = request;
  }

  /**
   * Clear scene change request
   */
  clearSceneChangeRequest(): void {
    this.gameState.temporaryInfo.sceneChangeRequest = null;
  }

  /**
   * Set transition flag to indicate a scene change has occurred
   */
  setTransitionFlag(isTransition: boolean): void {
    this.gameState.temporaryInfo.transition = isTransition;
  }

  /**
   * Clear transition flag
   */
  clearTransitionFlag(): void {
    this.gameState.temporaryInfo.transition = false;
  }

  /**
   * Set scene transition rejection info (when Director denies player's transition request)
   */
  setSceneTransitionRejection(reasoning: string): void {
    this.gameState.temporaryInfo.sceneTransitionRejection = {
      wasRequested: true,
      reasoning,
      timestamp: new Date()
    };
  }

  /**
   * Clear scene transition rejection
   */
  clearSceneTransitionRejection(): void {
    this.gameState.temporaryInfo.sceneTransitionRejection = null;
  }

  /**
   * Set narrative direction instruction from Director Agent
   */
  setNarrativeDirection(direction: string | null): void {
    this.gameState.temporaryInfo.narrativeDirection = direction;
  }

  /**
   * Clear narrative direction
   */
  clearNarrativeDirection(): void {
    this.gameState.temporaryInfo.narrativeDirection = null;
  }

  /**
   * Update current scenario based on player actions
   */
  updateScenarioState(scenarioUpdates: any): void {
    if (!scenarioUpdates || !this.gameState.currentScenario) return;

    // Update scenario description if provided
    if (scenarioUpdates.description) {
      // Record description change as a permanent scenario change so it persists across snapshots
      const descriptionChange = `Scene description updated: ${scenarioUpdates.description}`;
      this.addPermanentScenarioChange(descriptionChange);
    }

    // Update environmental conditions
    if (scenarioUpdates.conditions && Array.isArray(scenarioUpdates.conditions)) {
      for (const newCondition of scenarioUpdates.conditions) {
        const existingIndex = this.gameState.currentScenario.conditions.findIndex(
          condition => condition.type === newCondition.type
        );
        
        if (existingIndex >= 0) {
          // Update existing condition
          this.gameState.currentScenario.conditions[existingIndex] = newCondition;
        } else {
          // Add new condition
          this.gameState.currentScenario.conditions.push(newCondition);
        }
      }
    }

    // Add new events
    if (scenarioUpdates.events && Array.isArray(scenarioUpdates.events)) {
      this.gameState.currentScenario.events.push(...scenarioUpdates.events);
    }

    // Update exits/entrances
    if (scenarioUpdates.exits && Array.isArray(scenarioUpdates.exits)) {
      for (const exitUpdate of scenarioUpdates.exits) {
        if (!this.gameState.currentScenario.exits) {
          this.gameState.currentScenario.exits = [];
        }
        
        const existingIndex = this.gameState.currentScenario.exits.findIndex(
          exit => exit.direction === exitUpdate.direction
        );
        
        if (existingIndex >= 0) {
          // Update existing exit
          this.gameState.currentScenario.exits[existingIndex] = exitUpdate;
        } else {
          // Add new exit
          this.gameState.currentScenario.exits.push(exitUpdate);
        }
      }
    }

    // Update clue states
    if (scenarioUpdates.clues && Array.isArray(scenarioUpdates.clues)) {
      for (const clueUpdate of scenarioUpdates.clues) {
        const existingIndex = this.gameState.currentScenario.clues.findIndex(
          clue => clue.id === clueUpdate.id
        );
        
        if (existingIndex >= 0) {
          // Update existing clue
          this.gameState.currentScenario.clues[existingIndex] = {
            ...this.gameState.currentScenario.clues[existingIndex],
            ...clueUpdate
          };
        } else if (clueUpdate.id) {
          // Add new clue
          this.gameState.currentScenario.clues.push(clueUpdate);
        }
      }
    }
  }

  /**
   * Add permanent change to the scenario (scenario-level, shared across all timeline snapshots)
   * 
   * Note: Permanent changes are stored at the scenario level (not snapshot level).
   * - In memory: temporarily stored in currentScenario.permanentChanges
   * - On checkpoint: saved to the scenarios table and shared by all timeline snapshots
   * - On load: all snapshots of the same scenario will receive the same permanent changes
   */
  addPermanentScenarioChange(changeDescription: string): void {
    if (!this.gameState.currentScenario || !changeDescription) return;
    
    // Initialize permanentChanges array if it doesn't exist
    if (!this.gameState.currentScenario.permanentChanges) {
      this.gameState.currentScenario.permanentChanges = [];
    }
    
    // Add the permanent change to current snapshot's array (which represents scenario-level changes)
    // These changes will be persisted to the scenario level when checkpoint is created
    this.gameState.currentScenario.permanentChanges.push(changeDescription);
  }

  /**
   * Get current game state (read-only access)
   */
  getGameState(): Readonly<GameState> {
    return this.gameState;
  }
}
